#━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#               CREATED BY NAYAN PARMAR
#                      © 2025
#━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

name: layer_kit
description: A Flutter architecture package that combines Clean Architecture and MVVM patterns using Provider for state management.
version: 0.0.1
homepage: https://github.com/Parmar24c/layer_kit

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^2.4.0
  path: ^1.8.3
#  yaml: ^3.1.2
#  analyzer: ^5.13.0
  recase: ^4.1.0
#  dio: ^5.3.2
#  get_it: ^7.6.0
#  equatable: ^2.0.5
#  provider: ^6.0.5
#  injectable: ^2.3.0
#  json_annotation: ^4.8.1
#  dartz: ^0.10.1
#  internet_connection_checker:
  flutter_easy_routing: ^0.0.4
  responsive_theme: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.0

flutter:

executables:
  layer_kit: layer_kit