#━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#               CREATED BY NAYAN PARMAR
#                      © 2025
#━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

name: layer_kit
description: A Flutter architecture package that combines Clean Architecture and MVVM patterns using Provider for state management.
version: 1.0.2
homepage: https://github.com/Parmar24c/layer_kit

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^2.4.0
  path: ^1.8.3
  recase: ^4.1.0
  flutter_easy_routing: ^0.0.4
  responsive_theme: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.0

flutter:

executables:
  layer_kit: layer_kit