#━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#               CREATED BY NAYAN PARMAR
#                      © 2025
#━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


name: layer_kit_example
description: "Layer Kit Example"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.1

  dio: ^5.4.0

  easy_localization: ^3.0.7
  easy_localization_loader:

  fluttertoast: ^8.2.4

  get_it: ^7.6.4

  intl: ^0.19.0
  image_picker: ^1.0.5

  provider: ^6.1.1
  path_provider: ^2.1.1
  permission_handler: ^11.1.0

  shared_preferences: ^2.2.2
  share_plus: ^7.2.1
  skeletonizer: ^1.4.2

  toastification: ^2.3.0

  url_launcher: ^6.2.2
  url_strategy:

  layer_kit:
    path: "../"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/config/lang/

